name: fluttery_timber
description: Another Android Timber-like Flutter Package. I use Fluttery Timber in my projects. Hope you find it useful.
version: 0.0.6
homepage: https://github.com/iballan/fluttery_timber

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
